name: Build tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-without-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure -d V4L2 -d libpng -d jpeg -d tiff -d zlib -d libX11 -d freetype -d fontconfig -d pthread -d backtrace
      - name: make
        run: make
      - name: tests
        run: cd tests && ./runtests.py

  build-with-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update-apt-db
        run: sudo apt-get update
      - name: install-image-libs
        run: sudo apt-get install libjpeg-dev libpng-dev libgif-dev libtiff-dev libwebp-dev libarchive-dev
      - name: install-freetype-libs
        run: sudo apt-get install libfreetype6-dev libfontconfig-dev
      - name: install-backend-libs
        run: sudo apt-get install libx11-dev libxext-dev libsdl2-dev libaa1-dev libxcb1-dev libxcb-keysyms1-dev libxcb-shm0-dev
      - name: install-swig
        run: sudo apt-get install swig python-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: tests
        run: cd tests && ./runtests.py

  build-with-sdl-1-2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update-apt-db
        run: sudo apt-get update
      - name: install-sdl-1-2
        run: sudo apt-get install libsdl-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: tests
        run: cd tests && ./runtests.py
